__init__.py
base.py
test/test_semi_structured_datatypes.py

Added `VARIANT`, `OBJECT` and `ARRAY` datatype support.
Limitations:
* No Python native datatype conversion is included, but all of the semi-structured datatypes are treated as `str`. The applications must convert it to `json` if needed.
* No DML support either due to lack of standard INSERT syntax support, i.e., INSERT VALUES(). Instead, the applications have to construct a SQL using INSERT SELECT form.
See the test cases for details.

SNOW-24699: added VARIANT, OBJECT and ARRAY datatype support

---

base.py

Without this snowflake users cannot execute a copy statement from sql-alchemy.

Adding COPY reserved word into base.py

---

test/test_unit_url.py
util.py

This change defers password empty check to Python Connector so that `externalbrowser` authenticator can be used through SQLAlchemy.

Accept empty password and let Python Connector validate it

---

test/test_orm.py

Fixed the test case. The test db and schema names are in capital cases in travisCI, while my local and internal tests use the lower cases. The fix is ensure the lowercase to avoid quotes.

ensure lower case object identifier in test to get the consistent result

---

README.rst

Hiya!
I added an extra line in the readme that references the snowflake account name docs. It threw me off for a small amount of time because I didn't know the region had to be added and it was not mentioned in the documentation of this project. So this PR adds that.
Feel free to merge or decline! 😄

Add extra line on account name in readme

---

snowdialect.py

SQLAlchemy 1.4.0b1 throw `sqlalchemy.exc.ObjectNotExecutableError` any time `connection.execute` is called using an `AsyncConnection` on raw string SQL. This wraps the raw string SQL objects in `sqlalchemy.text` and updates the bind parameter syntax correspondingly to avoid this issue.

SNOW-271500 Update dialect to wrap raw SQL for SQLA 1.4

---

setup.py

With the release of `snowflake-sqlalchemy==1.2.5` the package now depends on `sqlalchemy>=1.4.0`. Since install_requires have not been updated to reflect this, the new 1.2.5 release will break all Snowflake customers' tasks pinning `sqlalchemy<1.4`. To highlight, this will likely break some of your customer tasks (it sure did for us) at runtime or (hopefully) during testing since pip install will not complain during installation.
This PR fixes `setup.py` to have the proper `install_requires`, but ideally, this PR should not be approved. It is not a good practice to force your customers to upgrade sqlalchemy due to a patch version change of your package. This is a pretty major break of backward compatibility, a potential break of production tasks, and an unexpected force-upgrade on your …

SNOW-396922 bump minimum sqlalchemy dependency version

---

snowdialect.py
test/test_orm.py

sqlalchemy 1.4 introduced a breaking change in the definition of returns_unicode_strings.
this change influences parsing Enum's encoded as string in snowflake. ﻿

SNOW-452342 fix breaking change introduced in sqlalchemy 1.4

---

base.py
test/test_orm.py

Fix issue #247 
This fixes the way _split_schema_by_dot changes the return value of the schema parameter from quoted_name to str.

fix orm schema translate map double quoting issue

---

snowdialect.py

When `supports_statement_cache` is unset in a sqlalchemy dialect, sqlalchemy emits a warning on first usage. Setting this attribute to `False` prevents this warning. See: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/265#issuecomment-1064446533.

SNOW-522232 fix: set `supports_statement_cache=False` in dialect class

---

base.py
test/test_compiler.py

SQLAlchemy operations for dropping table / column comments were failing because the default dialect implementation generates these commands:
```sql
COMMENT ON TABLE table1 IS NULL
COMMENT ON COLUMN table1.id IS NULL
```
Snowflake only accepts strings for comment values, so the queries failed with syntax errors.
I've also added schema to a compiler test table to verify that it creates correct statements with a non-default schema.

Fix comment dropping operations

---

snowdialect.py
test/test_core.py

SQLAlchemy expects foreign key reflection to set schemas which do not need specifying in the current database context (i.e. default schema or current schema) to be set to None. Without this, alembic migration keep re-creating foreign keys as it considers a referred table with a schema and without a schema two separate tables.
See [SQLAlchemy docs on reflection](https://docs.sqlalchemy.org/en/14/core/reflection.html#reflection-schema-qualified-interaction) for what is the expected behaviour of dialects.

Set foreign key referred schema to None when needed

---

DESCRIPTION.rst
base.py
custom_types.py
snowdialect.py
test/test_quote.py
test/test_sequence.py

Fixes SNOW-118945, #124 
The code is not doing correct in **_two_** aspects:
1. The first issue is that when we create a column with `Sequence`, the default value was not set correctly, it should not be set using "autoincrement" which failed to connect the column with the sequence.
- to fix the issue, we should use "default seq.nextval" to set as the column's default value.
- for more context please check doc here for "autoincrement" and "default" keyword: …

SNOW-118945: Fix ArgumentError where insert with autoincrement failed due to incompatible column type affinity

---

src/snowflake/sqlalchemy/base.py
tests/sqlalchemy_test_suite/test_suite.py

Fixes SNOW-629067
In pre execute:
- add a check whether double percents is used; whether the statement is compiled; whether the statement is an insertion 
- check whether it's a insert batch, insert batch needs to be handled with care because of the connector implementation

SNOW-629067 connector executemany handle escaping double percents when no params

---

DESCRIPTION.md
src/snowflake/sqlalchemy/custom_types.py
src/snowflake/sqlalchemy/requirements.py
src/snowflake/sqlalchemy/snowdialect.py
src/snowflake/sqlalchemy/util.py
tests/sqlalchemy_test_suite/test_suite.py
tests/test_core.py

Fixes SNOW-640136
- To comply with the sqlalchemy test suites
-  changes were made to datetime/timestamp result processor to handle datetime/timestamp values. However, this turns out to be a behavior breaking change so reverting it.
- changes were made to keep the order of the primary keys and foreign keys returned by `inspect.get_foreign_keys/get_pk_constrains` the same as the sequence orders of how they were defined in the Snowflake DB. However, this turns out to be a behavior breaking change so reverting …

SNOW-640136: Revert breaking changes in snowflake-sqlalchemy v1.4.0

---

README.md
src/snowflake/sqlalchemy/util.py
tests/test_unit_url.py

Fixes SNOW-538310
SQLAlchemy requires the db password to be escaped if it's containing special characters. Adding instruction in our readme/doc.

SNOW-538310: Error when using create_engine() and password containing % character

---

tox.ini

Fixes SNOW-638966
update junit file name so that the test data could be collected.
the previous naming pattern `junit.{envname}.xml`, the `.` between `junit` and `{envname}` leading the infra unable to match the report and upload to s3, which further makes the test data could not be collected by snowhouse.

SNOW-638966: SQLAlchemy jobs are not uploading test results to Tests table in snowhouse

---

DESCRIPTION.md
setup.cfg
src/snowflake/sqlalchemy/snowdialect.py
tests/test_core.py

Fixes SNOW-652674
trying to fix issue: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/340, and based on discussion in https://github.com/sqlalchemy/sqlalchemy/discussions/8444.
column name could be an empty string, and to fix it, we should check if string is empty and return empty string accordingly when normalizing/denormalizing names.

SNOW-652674: normalize name and denormalize name should handle empty string

---

.pre-commit-config.yaml
DESCRIPTION.md
src/snowflake/sqlalchemy/util.py

Fixes #350 
Removes the import of a private function that was removed in the release of SQLAlchemy 1.4.42 and adds this directly to the codebase.

SNOW-679045: _rfc_1738_quote is no longer available in sqlalchemy 1.4.42

---

.github/workflows/build_test.yml
tox.ini

Fixes SNOW-706024
starting from tox 4.0.0rc2 (included), the `extras` in the `tox.ini` is not working correctly, which in our cases, `snowpark-connector-pyhon[pandas]<3.0.0` is not installed.
pin tox to 4.0.0rc1 first

SNOW-706024: Fix failing github build and test

---

src/snowflake/sqlalchemy/snowdialect.py
tests/test_core.py

Fixes #386 
"host" connection URL parameter is no longer assumed to be always there

fix create_engine("snowflake://").dialect

---

src/snowflake/sqlalchemy/base.py
tests/test_compiler.py

Fixes #395
implements `SnowflakeCompiler.visit_now_func` to render `func.now()` as `CURRENT_TIMESTAMP`

render func.now() as CURRENT_TIMESTAMP

---

DESCRIPTION.md
src/snowflake/sqlalchemy/__init__.py
src/snowflake/sqlalchemy/base.py
src/snowflake/sqlalchemy/custom_types.py
src/snowflake/sqlalchemy/snowdialect.py
tests/test_core.py
tests/test_custom_types.py
tests/test_geometry.py
tests/util.py

Fixes SNOW-871115
echoing PR https://github.com/snowflakedb/snowflake-sqlalchemy/pull/427 with a couple of more changes

SNOW-871115: add geometry support

---

.github/workflows/build_test.yml
.gitmodules
tox.ini

Fixes SNOW-897870: remove connector submodule in sqlalchemy

SNOW-897870: remove connector submodule in sqlalchemy

---

.github/workflows/build_test.yml

SNOW-1056848-missing-test-action-output: remove TOX_PARALLEL_NO_SPINNER env variable
Fixes # SNOW-1056848
`TOX_PARALLEL_NO_SPINNER` variable removed to [restore](https://github.com/tox-dev/tox/issues/3193) action output

SNOW-1056848-missing-test-action-output: remove TOX_PARALLEL_NO_SPINNER

---

.github/workflows/build_test.yml
DESCRIPTION.md
pyproject.toml
src/snowflake/sqlalchemy/version.py

Fixes #485 
Moved SQLAlchemy version pinning from env settings to project metadata.
Added CI job for build and installation validation.

SNOW-1324105-dependency-pinning: move versions pinning from project env to metadata

---

.github/workflows/changelog.yml
.github/workflows/create_req_files.yml
.github/workflows/jira_close.yml
.github/workflows/jira_issue.yml
.github/workflows/python-publish.yml
.github/workflows/snyk-issue.yml
.github/workflows/snyk-pr.yml

Fixes #NNNN
Updated outdated GH actions

mraba/gh-actions-update: bump github actions versions to latest

---

src/snowflake/sqlalchemy/base.py
tests/test_sequence.py

Fixes #436 
[CREATE TABLE DDL](https://docs.snowflake.com/en/sql-reference/sql/create-table#optional-parameters) supports optional `ORDER | NOORDER` value for `AUTOINCREMENT | IDENTITY` sequences on a column. Before this change, using a column with a sequence like `Column(NUMBER, Identity(start=1, increment=1, order=True)` would default to session parameter [NOORDER_SEQUENCE_AS_DEFAULT](https://docs.snowflake.com/en/sql-reference/parameters#label-noorder-sequence-as-default) `TRUE` by default which would …

Add ability to set ORDER / NOORDER sequence on columns with IDENTITY

---

.github/workflows/build_test.yml
DESCRIPTION.md
README.md
ci/build.sh
ci/test_linux.sh
pyproject.toml

SNOW-1516075
Use SQLAlchemy 2.0 as default dependency.
SQLAlchemy 1.4 moved as extra dependency for test cases and checks.

SNOW-1516075: use SQLALchemy 2.0 as default dependency

---

.github/workflows/python-publish.yml

Fixes #NNNN
Signing artifacts with cosign before publishing them. The signing has the next steps:
- sign artifacts
- verify signature using bundle file
- verify signature using public certificate and public key
- copy artifacts to the release tag

SNOW-685438: Sign artifacts before publish

---

pyproject.toml
tests/test_custom_types.py
tests/test_orm.py

[
Jira Ticket](https://snowflakecomputing.atlassian.net/browse/SNOW-1482251)
It add a couple of test to try max lob size feature

Add tests to try max lob size in memory feature

---

DESCRIPTION.md
README.md
src/snowflake/sqlalchemy/__init__.py
src/snowflake/sqlalchemy/base.py
src/snowflake/sqlalchemy/sql/custom_schema/__init__.py
src/snowflake/sqlalchemy/sql/custom_schema/clustered_table.py
src/snowflake/sqlalchemy/sql/custom_schema/dynamic_table.py
src/snowflake/sqlalchemy/sql/custom_schema/hybrid_table.py
src/snowflake/sqlalchemy/sql/custom_schema/iceberg_table.py
src/snowflake/sqlalchemy/sql/custom_schema/options/__init__.py
src/snowflake/sqlalchemy/sql/custom_schema/options/cluster_by_option.py
src/snowflake/sqlalchemy/sql/custom_schema/options/table_option.py
src/snowflake/sqlalchemy/sql/custom_schema/snowflake_table.py
src/snowflake/sqlalchemy/sql/custom_schema/table.py
src/snowflake/sqlalchemy/sql/custom_schema/table_from_query.py
tests/__snapshots__/test_core.ambr
tests/custom_tables/__snapshots__/test_compile_iceberg_table.ambr
tests/custom_tables/__snapshots__/test_compile_snowflake_table.ambr
tests/custom_tables/__snapshots__/test_create_iceberg_table.ambr
tests/custom_tables/__snapshots__/test_create_snowflake_table.ambr
tests/custom_tables/__snapshots__/test_reflect_snowflake_table.ambr
tests/custom_tables/test_compile_iceberg_table.py
tests/custom_tables/test_compile_snowflake_table.py
tests/custom_tables/test_create_iceberg_table.py
tests/custom_tables/test_create_snowflake_table.py
tests/custom_tables/test_reflect_snowflake_table.py
tests/test_core.py

Fixes [SNOW-1514024](https://snowflakecomputing.atlassian.net/browse/SNOW-1514024)
- Add support for Iceberg Table with Snowflake Catalog
- Add ClusterByOption and SnowflakeTable to create normal tables
- Fix snowflake_clusterby not working with explicit expressions 
[SNOW-1514024]: https://snowflakecomputing.atlassian.net/browse/SNOW-1514024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for iceberg table with snowflake catalog

---

DESCRIPTION.md
src/snowflake/sqlalchemy/base.py
src/snowflake/sqlalchemy/custom_commands.py
tests/test_copy.py

Fixes https://github.com/snowflakedb/snowflake-sqlalchemy/issues/430
Co-authored by @azban 
This adds an argument to CopyInto which can be used to specify the PARTITION BY value.

SNOW-878116 Add support for PARTITION BY to COPY INTO location

---

DESCRIPTION.md
pyproject.toml
src/snowflake/sqlalchemy/parser/custom_type_parser.py
src/snowflake/sqlalchemy/snowdialect.py
tests/conftest.py
tests/test_index_reflection.py

Fixes SNOW-1843517
Fixed issue where indexes now correctly reflect their associated columns.
Resolved caching issue for table prefixes.

Improve index reflection 

---

DESCRIPTION.md
README.md
src/snowflake/sqlalchemy/base.py
src/snowflake/sqlalchemy/custom_types.py
src/snowflake/sqlalchemy/parser/custom_type_parser.py
tests/__snapshots__/test_structured_datatypes.ambr
tests/test_structured_datatypes.py
tests/test_unit_structured_types.py

Fixes SNOW-1776333
Add support for Structured Array in SqlAlchemy

SNOW-1776333 Add support for ARRAY

---

DESCRIPTION.md
pyproject.toml
src/snowflake/sqlalchemy/base.py
src/snowflake/sqlalchemy/snowdialect.py
tests/conftest.py
tests/test_compiler.py
tests/test_core.py

Fixes #543 
The default behavior of the flag div_is_floor_div was changed to False. This ensures that Python and Snowflake operators match the right division. In this first version a flag would be added `force_div_is_floor_div` to override the current behavior.

Added flag to allow override SnowflakeDialect div_is_floor_div flag

---

DESCRIPTION.md
src/snowflake/sqlalchemy/sql/custom_schema/hybrid_table.py
tests/custom_tables/__snapshots__/test_compile_hybrid_table.ambr
tests/custom_tables/test_compile_hybrid_table.py

Fixes #NNNN
Original [PR](https://github.com/snowflakedb/snowflake-sqlalchemy/pull/571) 
Co-authored by [benvdh-incentro](https://github.com/benvdh-incentro)

Add structured type support for hybrid tables

---

DESCRIPTION.md
README.md

SNOW-1758365 Update README.md to include instructions on how to verify package signatures using cosign.

---

DESCRIPTION.md
src/snowflake/sqlalchemy/name_utils.py
src/snowflake/sqlalchemy/parser/custom_type_parser.py
src/snowflake/sqlalchemy/snowdialect.py
src/snowflake/sqlalchemy/structured_type_info_manager.py
tests/conftest.py
tests/sqlalchemy_test_suite/test_suite_20.py
tests/test_core.py
tests/test_structured_datatypes.py
tests/test_transactions.py

Map and Array type information is not stored in information_schema.columns table, so it is required to execute a DESC command for tables with structured types. If table is drop once SELECT on columns table but before executing DESC an exception is raised. Fix basically consists in caching the exception and ignoring the table because it does not exists anymore
Additionally updated test cases broken from a SQLAlchemy update.
Fixes JIRA #606
- [ X] I am adding a new automated test(s) to verify correctness of my new code
3. Please describe how your code solves the …

Fixing exception while getting info for StructuredType columns.
