snowflakedb/snowflake-sqlalchemy

base.py
Add support for adding `CLUSTER BY` syntax to `CREATE TABLE`:
```
>>> import sqlalchemy as sa
>>> from sqlalchemy.schema import CreateTable
>>> engine = sa.create_engine('snowflake://om1')
>>> metadata = sa.MetaData()
>>> user = sa.Table(
...     'user',
...     metadata,
...     sa.Column('id', sa.Integer, primary_key=True),
...     sa.Column('name', sa.String),
...     snowflake_clusterby=['id', 'name']
... )
>>> print(CreateTable(user).compile(engine))
CREATE TABLE "user" (
id INTEGER NOT NULL AUTOINCREMENT,
name VARCHAR,
PRIMARY KEY (id)
) CLUSTER BY (id, name)
```
=> add support for `CREATE TABLE … CLUSTER BY`

base.py, test/test_core.py
=> SNOW-38109: foreign key names should be normalized

base.py, setup.py, test/test_core.py
=> SNOW-38110: Fixed #24: Snowflake Dialect should set the default schema

base.py
Mitigate the issue #29 and #30
=> Cache current database and schema for repeated use

README.rst, base.py, test/conftest.py, test/test_core.py
The method should have included kw parameters.
=> Fixed reflection cache

README.rst
=> added alembic usage to the doc

README.rst
=> added role paramer to doc

base.py, test/test_core.py
Note this fix will change the return value of get_primary_keys. The existing applications that depend on a wrong behavior of get_primary_keys should replace with get_pk_constraint
=> Fixed the return value of get_pk_constraint. 

.travis.yml, test/test_qmark.py
botocore 1.9.8's python-dateutil requirement caused problem. This is workaround.
=> Workaround botocore 1.9.8

util.py
https://github.com/snowflakedb/snowflake-connector-python/pull/86
https://github.com/snowflakedb/snowflake-connector-python/pull/89
=> make username optional. escape password in URL

README.rst
Updated to include key pair authentication support.
=> Doc: Added key pair authentication support

base.py, test/test_compiler.py
=> preserve quote label

test/conftest.py
The new version of pytest raise errors if fixture is used as a method.
=> fixed pytest error

.travis.yml, scripts/install.sh, scripts/run_travis.sh, setup.py
Added Python 3.6 and 3.7 support
=> Add python37

base.py, test/__init__.py, test/conftest.py, test/test_core.py
Fixing the regression in 1.1.7
=> Fix snow 67068

.github/actions/gajira-issue-update/dist/index.js
This PR adds the missing JS dist folder to allow Jira create to run
=> SNOW-197364 add missing dist folder

DESCRIPTION.rst, __init__.py, setup.py, snowdialect.py, test/conftest.py, test/test_core.py, test/test_unit_cte.py, version.py
=> Release 1.2.4

.github/CODEOWNERS
=> SNOW-265864 Added CODEOWNERS

.github/CODEOWNERS
SNOW-265864
Updating CODEOWNERS as per @sfc-gh-kwagner 's request
=> SNOW-265864 updating CODEOWNERS

scripts/py_exec.sh, snowdialect.py, test/test_core.py, test/test_pandas.py, test/test_qmark.py, test/test_semi_structured_datatypes.py, test/test_timestamp.py
Syncing changes from monorepo to this one.
The first commit is from last year (it slipped through the crack until now) and more recent changes
=> SNOW-368566 syncing from monorepo

.github/workflows/jira_issue.yml
Committed via https://github.com/asottile/all-repos
=> SNOW-499170 Bringing GH actions up-to-date with Python connector's

snowdialect.py, test/test_core.py
The snowflake dialect has identifier max length of 255 according to [this page of the official documentation](https://docs.snowflake.com/en/sql-reference/identifiers.html). However, in this library, the limit was set to 65535. This causes issues when trying to use an sqlalchemy [naming convention](https://docs.sqlalchemy.org/en/14/core/constraints.html?highlight=naming%20convention#configuring-constraint-naming-conventions), because while sqlalchemy would take into account the identifier length and shorten long names where needed, the higher limit will make it think that there is no shortening needed. Without the shortening logic, sqlalchemy will emit queries that will error out because of hitting the identifier limts.
This PR updates the limit, adds a test so that the naming convention …
=> SNOW-576659 fix dialect identifier max length and relevant schema introspection

.github/dependabot.yml, .github/pull_request_template.md, .github/workflows/jira_issue.yml, .gitignore, test/.gitignore
SNOW-582913
Bringing various GitHub settings up to date, some of these come from the [snowflakedb/snowflake-connector-python](https://github.com/snowflakedb/snowflake-connector-python) and some are personal improvements
=> SNOW-582913 bringing GH settings up to date

.github/workflows/jira_issue.yml
Fixes SNOW-582913
Adjusting assignee of generated Jiras.
=> SNOW-582913 adding multiple issue templates

.github/workflows/jira_issue.yml
Fixes SNOW-582913
Updating Jira automation assignee
=> SNOW-582913 assignee update

README.rst
Fixes #NNNN
Just updating the codecov shield to show actual coverage
=> update codecov shield

ci/build.sh, ci/build_docker.sh, ci/docker/sqlalchemy_build/Dockerfile, ci/docker/sqlalchemy_build/scripts/entrypoint.sh, ci/set_base_image.sh
Partially fixes SNOW-582912
In this PR I add necessary scripts for our new Jenkins build to start building from this public repository
=> SNOW-582912 adding scripts for Jenkins builds

.github/workflows/create_req_files.yml
=> SNOW-155324 Create a test requirements file including SQLAlchemy

.pre-commit-config.yaml, LICENSE.txt, README.md, license_header.txt, setup.py, src/snowflake/sqlalchemy/__init__.py, src/snowflake/sqlalchemy/base.py, src/snowflake/sqlalchemy/custom_commands.py, src/snowflake/sqlalchemy/custom_types.py, src/snowflake/sqlalchemy/snowdialect.py, src/snowflake/sqlalchemy/util.py, tests/conftest.py, tests/test_compiler.py, tests/test_copy.py, tests/test_core.py, tests/test_create.py, tests/test_custom_types.py, tests/test_geography.py, tests/test_multivalues_insert.py, tests/test_orm.py, tests/test_pandas.py, tests/test_qmark.py, tests/test_quote.py, tests/test_semi_structured_datatypes.py, tests/test_sequence.py, tests/test_timestamp.py, tests/test_unit_core.py, tests/test_unit_cte.py, tests/test_unit_types.py, tests/test_unit_url.py
SNOW-619729:
Add license insert hook to pre-commit which automatically inserts the license for us into each file.
=> SNOW-619729 Add license insert hook to pre-commit

.github/workflows/create_req_files.yml
=> update secret reference in create_req_files.yml

tested_requirements/requirements_310.reqs, tested_requirements/requirements_37.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> Update requirements files

src/snowflake/sqlalchemy/base.py, src/snowflake/sqlalchemy/custom_types.py, src/snowflake/sqlalchemy/provision.py, src/snowflake/sqlalchemy/requirements.py, src/snowflake/sqlalchemy/snowdialect.py, src/snowflake/sqlalchemy/util.py, tests/sqlalchemy_test_suite/conftest.py, tests/sqlalchemy_test_suite/test_suite.py, tests/test_core.py
Fixes SNOW-619615
| total sqlalchemy tests | picked by us | passed | skipped |
| ------- | ------ | -------- | ------ |
| 560 | 501 | 317 | 184 | 
We pickled 501 tests provided by sqlalchemy test suites -- total is 560, index related tests are removed as not supported in snowflake. There're in total 184 tests being skipped, majorly falling into 5 categories:
1. not supported by service
2. potential service side issue/unclear behavior
3. connector issue
4. connector missing feature
5. sqlalchemy missing feature
For 1 and 2, please refer to the `requirements.py` for detailed information, and 3, 4, 5 will be …
=> SNOW-619615: SQLAlchemy dialect compliance

DESCRIPTION.md, tests/sqlalchemy_test_suite/conftest.py, tests/util.py
=> SNOW-629074 unstable sqlalchemy tests due to missing table/sequence

.github/workflows/python-publish.yml
=> SNOW-632805 Publish to pypi on release tag creation

DESCRIPTION.md, setup.cfg, src/snowflake/sqlalchemy/snowdialect.py, tests/conftest.py, tests/test_compiler.py, tests/test_copy.py, tests/test_core.py, tests/test_geography.py, tests/test_multivalues_insert.py, tests/test_orm.py, tests/test_pandas.py, tests/test_qmark.py, tests/test_semi_structured_datatypes.py, tests/test_sequence.py, tests/test_timestamp.py, tests/test_unit_core.py, tests/test_unit_cte.py, tox.ini
SNOW-629084
Update tests and implementation to meet the requirements of sqlalchemy 2.0, making sure there is no warning if run in 2.0 mode.
=> SNOW-629084 follow sqlalchemy 2.0 migration guide to verify the requirements are met

tests/test_core.py
Fixes SNOW-637204
add naming randomization to stabilize tests that will be run in parallel by multiple jenkins jobs.
=> SNOW-637204: Fix unstable sqlachemy test test_special_schema_character 

DESCRIPTION.md
=> SNOW-646724: Release update for 1.4.1

.github/workflows/build_test.yml, .github/workflows/snyk-issue.yml, .pre-commit-config.yaml, src/snowflake/sqlalchemy/base.py, src/snowflake/sqlalchemy/custom_commands.py, src/snowflake/sqlalchemy/snowdialect.py, src/snowflake/sqlalchemy/util.py, tests/conftest.py, tests/test_copy.py, tests/test_core.py, tests/test_geography.py, tests/test_multivalues_insert.py, tests/test_orm.py, tests/test_pandas.py, tests/test_qmark.py, tests/test_semi_structured_datatypes.py, tests/test_sequence.py, tests/test_timestamp.py, tox.ini
Fixes SNOW-633094
Improve code quality including using f string, formatting tests.
=> SNOW-633094: Switch all source code to use f-strings and with statements

.gitignore, tests/test_pandas.py
Fixes [snowflake-connector-python #679](https://github.com/snowflakedb/snowflake-connector-python/issues/679)
Tests added for additional arguments of `write_pandas` exposed in `pd_writer` from `snowflake-connector-python`.
=> SNOW-344567: Added tests for updated pd_writer in snowflake-connector

DESCRIPTION.md
=> SNOW-679432: Release 1.4.3

DESCRIPTION.md, setup.cfg, src/snowflake/sqlalchemy/base.py, src/snowflake/sqlalchemy/util.py, tests/test_pandas.py
Fixes SNOW-638845
Fixed a bug that identifiers having percents in a non-compiled statement was interpolated.
=> SNOW-638845  ValueError: unsupported format character with version 1.4.0

tests/test_pandas.py
Fixes SNOW-638845
fixed tests for sqlalchemy v20 and add one more test cases.
=> SNOW-638845: ValueError: unsupported format character with version 1.4.0

DESCRIPTION.md
=> SNOW-693793 Bump Up SQL Alchemy Version to 1.4.4

.pre-commit-config.yaml
=> SNOW-696321 fix flake8 dep

ci/test.sh
Fixes #SNOW-690378
updating s3 buckets for sfc dev2 move
=> SNOW-690378 s3 bucket move

DESCRIPTION.md, setup.cfg, src/snowflake/sqlalchemy/_constants.py, src/snowflake/sqlalchemy/snowdialect.py, src/snowflake/sqlalchemy/util.py, tests/test_core.py
Fixes #SNOW-69880
set connection application so that snowflake knows the source
=> SNOW-698806: add usage telemetry information

.github/workflows/build_test.yml, tox.ini
=> SNOW-706115: Unpin tox

DESCRIPTION.md
=> V1.4.6 release preparation

.github/workflows/create_req_files.yml, ci/docker/sqlalchemy_build/Dockerfile, ci/test_linux.sh, tox.ini
=> SNOW-741094: add py311 to matrix

.github/workflows/build_test.yml, DESCRIPTION.md, setup.cfg, setup.py, src/snowflake/sqlalchemy/_constants.py, src/snowflake/sqlalchemy/snowdialect.py, src/snowflake/sqlalchemy/version.py, tests/conftest.py, tests/test_core.py
Fixes #SNOW-716374, pending service change and https://github.com/snowflakedb/snowflake-sqlalchemy/pull/369
=> SNOW-716374: reapply telemetry change of application and test panda arrow result format

.github/workflows/stale_issue_bot.yml
=> SNOW-760002: add stale issue clean bot

.github/workflows/changelog.yml
Committed via https://github.com/asottile/all-repos
=> changelog bot public repositories

DESCRIPTION.md, src/snowflake/sqlalchemy/base.py, src/snowflake/sqlalchemy/custom_commands.py, tests/test_create.py
=> Test pr 418

DESCRIPTION.md, src/snowflake/sqlalchemy/base.py
=> SNOW-857216: fix compatibility issue with sqlalchemy 1.4.49

.github/workflows/cla_bot.yml
Fixes #NNNN
CLA document is moved to a new repo, we need to update the link. This should be automated in the future.
=> Update CLA document link

DESCRIPTION.md, src/snowflake/sqlalchemy/version.py
=> SNOW-897060 - Release 1.5.0

DESCRIPTION.md, src/snowflake/sqlalchemy/base.py, src/snowflake/sqlalchemy/util.py, tests/test_compiler.py, tests/test_orm.py
Fixes SNOW-876389, fix compatibility with [BCR-1057](https://docs.snowflake.com/en/release-notes/bcr-bundles/2023_04/bcr-1057)
[BCR-1057]: https://snowflakecomputing.atlassian.net/browse/BCR-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-876389: compatibility with bcr-1057 on outer lateral table join

DESCRIPTION.md, src/snowflake/sqlalchemy/version.py
Fixes #NNNN
Getting ready to release `v1.5.1`
=> Bumped up SQLAlchemy PATCH version from 1.5.0 to 1.5.1

DESCRIPTION.md
Fixes #NNNN
Added release date and format version string
=> mraba/description-file-update: add release date and format version string

.github/CODEOWNERS
Fixes #NNNN
Updated CODEOWNERS file  replacing `snowpark-python-api` team with `snowcli`
=> mraba/codeowners-update: replace snowpark-pytho-api with snowcli

.pre-commit-config.yaml, pyproject.toml, snyk/requirements.txt, snyk/requiremtnts.txt, snyk/update_requirements.py
Fixes #NNNN
Added `requirements.txt` in for snyk scanning.
=> mraba/snyk-support-requirements: add requirements.txt file for snyk scanning

DESCRIPTION.md
SNOW-1516075
Setting release date to July, 8th
=> SNOW-1516075: set release date to July 8th

ci/build.sh
SNOW-1519492
update `export PATH` in `ci\build.sh` resolved failing whl builds
=> SNOW-1519492: add export PATH in build.sh script

pyproject.toml, tox.ini
Fixes #SNOW-1519635
Added required tomlkit package to tox testing setup.
=> SNOW-1519635: skip dialect tests in snowflake tests

tox.ini
Fixes #SNOW-1519766
Remove `tomlkit` version from tox configuration
=> SNOW-1519766: drop tomlkit version for fix_lint

.github/workflows/python-publish.yml
Fixes #SNOW-1632311
There is an error in the signing step. When validating the signature it uses the github action name used for signing. That name is incorrect and this action will fail. The fix is to use the correct name.
=> SNOW-1632311: Update python-publish.yml with the correct name

DESCRIPTION.md
=> Update release notes date

README.md
=> Update README.md with Custom Tables documentation

DESCRIPTION.md, src/snowflake/sqlalchemy/version.py
=> Update release version

DESCRIPTION.md, src/snowflake/sqlalchemy/snowdialect.py, tests/test_transactions.py
Fixes SNOW-1846847 
Related issue: https://snowflake.discourse.group/t/sqlalchemy-how-to-remove-rollback-statements-for-simple-select-statements/13668
This PR doesn't fix unnecessary emitted rollbacks, instead it add support for setting autocommit isolation level when using engine.connect() funcition.
for example:
```
with engine_testaccount.connect().execution_options(
isolation_level="AUTOCOMMIT"
);
```
=> SNOW-1846847 Add support for autocommit

DESCRIPTION.md, src/snowflake/sqlalchemy/snowdialect.py, tests/test_core.py
Fixes #NNNN
This PR has been duplicated to execute the necessary tests and merge the changes. For reference, the original PR can be found here: [#563](https://github.com/snowflakedb/snowflake-sqlalchemy/pull/563).
Co-authored by @TrangPham
=> Fix return value of snowflake get_table_names

DESCRIPTION.md, src/snowflake/sqlalchemy/base.py, tests/test_compiler.py
Fixes #565
Fix incorrect quoting of identifiers with `_` as initial character.
=> SNOW-1871392 Fix incorrect quoting of identifiers with `_` as initial character.

DESCRIPTION.md, src/snowflake/sqlalchemy/base.py, src/snowflake/sqlalchemy/custom_types.py, tests/__snapshots__/test_structured_datatypes.ambr, tests/test_structured_datatypes.py
=> SNOW-1871582 Fix support for SA array

DESCRIPTION.md, src/snowflake/sqlalchemy/version.py
=> Update release notes

DESCRIPTION.md, tests/conftest.py, tests/custom_tables/test_create_iceberg_table.py, tests/test_pandas.py
=> Skip failing test

DESCRIPTION.md
=> Fix small typo

DESCRIPTION.md, src/snowflake/sqlalchemy/version.py
=> Update version.py with 1.7.4
